name: Generate and Upload PDF

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - main 
jobs:
  generate_pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt 

      - name: Generate CV
        run: python get_papers.py

      - name: Render CV
        run: rendercv render "Sergey_Isaev_CV.yaml"

      - name: Configure Git
        run: |
          git config --unset-all http.https://github.com/.extraheader
          git config --global user.name "serjisa"
          git config --global user.email "serj.hoop@gmail.com"

      - name: Clone Target Repository
        run: |
          git clone https://github.com/serjisa/serjisa.github.io
          cp rendercv_output/Sergey_Isaev_CV.pdf serjisa.github.io/assets/pdf/cv.pdf

      - name: Push PDF to Target Repository
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_SECRET }}
        run: |
          cd serjisa.github.io
          git add .
          git commit -m "Update PDF - $(date +'%Y-%m-%d')"
          git push https://$GITHUB_TOKEN@github.com/serjisa/serjisa.github.io master
